-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, SUBSTR(START_DATE,1,10) as START_DATE, SUBSTR(END_DATE,1,10) as END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC